# Generated by Django 3.1.1 on 2023-08-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[('Helper', 'Helper'), ('Faculty', 'Faculty')], max_length=100),
        ),
    ]
