# Generated by Django 3.1.1 on 2023-08-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20230817_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[('Helper', 'Helper'), ('Faculty/Teacher', 'Faculty/Teacher')], max_length=100),
        ),
    ]
