# Generated by Django 3.1.1 on 2023-08-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20230817_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='subject_expertise',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('English', 'English'), ('Hindi', 'Hindi'), ('Sanskrit', 'Sanskrit'), ('Computer', 'Computer'), ('Social Science', 'Social Science'), ('Other', 'Other')], max_length=100),
        ),
    ]
